In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

from statsmodels.tsa.arima.model import ARIMA

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

In [3]:
df = pd.read_csv(r"D:\Projects\ML PROJECT 2\dataset\election_data.csv")

In [4]:
df.head()

,st_name,year,pc_no,pc_name,pc_type,cand_name,cand_sex,partyname,partyabbre,totvotpoll,electors
0,Andaman & Nicobar Islands,1977,1,Andaman & Nicobar Islands,GEN,K.R. Ganesh,M,Independents,IND,25168,85308
1,Andaman & Nicobar Islands,1977,1,Andaman & Nicobar Islands,GEN,Manoranjan Bhakta,M,Indian National Congress,INC,35400,85308
2,Andaman & Nicobar Islands,1980,1,Andaman & Nicobar Islands,GEN,Ramesh Mazumdar,M,Independents,IND,109,96084
3,Andaman & Nicobar Islands,1980,1,Andaman & Nicobar Islands,GEN,Alagiri Swamy,M,Independents,IND,125,96084
4,Andaman & Nicobar Islands,1980,1,Andaman & Nicobar Islands,GEN,Kannu Chemy,M,Independents,IND,405,96084

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 73081 entries, 0 to 73080
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   st_name     73081 non-null  str
 1   year        73081 non-null  int64
 2   pc_no       73081 non-null  int64
 3   pc_name     73081 non-null  str
 4   pc_type     65011 non-null  str
 5   cand_name   73081 non-null  str
 6   cand_sex    72539 non-null  str
 7   partyname   73081 non-null  str
 8   partyabbre  73081 non-null  str
 9   totvotpoll  73081 non-null  int64
 10  electors    73081 non-null  int64
dtypes: int64(4), str(7)
memory usage: 6.1 MB

In [6]:
df.describe()

               year         pc_no     totvotpoll      electors
count  73081.000000  73081.000000   73081.000000  7.308100e+04
mean    1996.779505     22.311490   49834.760266  1.122277e+06
std       10.432527     19.039793  104893.319706  3.560049e+05
min     1977.000000      1.000000       0.000000  1.947100e+04
25%     1989.000000      7.000000     872.000000  9.129850e+05
50%     1996.000000     18.000000    2743.000000  1.099503e+06
75%     2004.000000     33.000000   19185.000000  1.329086e+06
max     2014.000000     85.000000  863358.000000  3.368399e+06

In [7]:
df.isnull().sum()

st_name          0
year             0
pc_no            0
pc_name          0
pc_type       8070
cand_name        0
cand_sex       542
partyname        0
partyabbre       0
totvotpoll       0
electors         0
dtype: int64

In [10]:
# Fill numeric columns with 0
num_cols = df.select_dtypes(include=['number']).columns
df[num_cols] = df[num_cols].fillna(0)

# Fill text columns with 'Unknown'
str_cols = df.select_dtypes(include=['object', 'string']).columns
df[str_cols] = df[str_cols].fillna('Unknown')